/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...path]': RouteRecordInfo<'/[...path]', '/:path(.*)', { path: ParamValue<true> }, { path: ParamValue<false> }>,
    '/404': RouteRecordInfo<'/404', '/404', Record<never, never>, Record<never, never>>,
    '/about/': RouteRecordInfo<'/about/', '/about', Record<never, never>, Record<never, never>>,
    '/albums/': RouteRecordInfo<'/albums/', '/albums', Record<never, never>, Record<never, never>>,
    '/albums/minecraft': RouteRecordInfo<'/albums/minecraft', '/albums/minecraft', Record<never, never>, Record<never, never>>,
    '/albums/omori': RouteRecordInfo<'/albums/omori', '/albums/omori', Record<never, never>, Record<never, never>>,
    '/archives/': RouteRecordInfo<'/archives/', '/archives', Record<never, never>, Record<never, never>>,
    '/bangumi/': RouteRecordInfo<'/bangumi/', '/bangumi', Record<never, never>, Record<never, never>>,
    '/categories/': RouteRecordInfo<'/categories/', '/categories', Record<never, never>, Record<never, never>>,
    '/fc/': RouteRecordInfo<'/fc/', '/fc', Record<never, never>, Record<never, never>>,
    '/links/': RouteRecordInfo<'/links/', '/links', Record<never, never>, Record<never, never>>,
    '/moment/': RouteRecordInfo<'/moment/', '/moment', Record<never, never>, Record<never, never>>,
    '/page/[page]': RouteRecordInfo<'/page/[page]', '/page/:page', { page: ParamValue<true> }, { page: ParamValue<false> }>,
    '/policies/privacy': RouteRecordInfo<'/policies/privacy', '/policies/privacy', Record<never, never>, Record<never, never>>,
    '/posts/git-tongbu': RouteRecordInfo<'/posts/git-tongbu', '/posts/git-tongbu', Record<never, never>, Record<never, never>>,
    '/posts/hexo-beiwang': RouteRecordInfo<'/posts/hexo-beiwang', '/posts/hexo-beiwang', Record<never, never>, Record<never, never>>,
    '/posts/markdown-biaotiyufa': RouteRecordInfo<'/posts/markdown-biaotiyufa', '/posts/markdown-biaotiyufa', Record<never, never>, Record<never, never>>,
    '/posts/markdown-duanluoyufa': RouteRecordInfo<'/posts/markdown-duanluoyufa', '/posts/markdown-duanluoyufa', Record<never, never>, Record<never, never>>,
    '/posts/markdown-dulanbiao': RouteRecordInfo<'/posts/markdown-dulanbiao', '/posts/markdown-dulanbiao', Record<never, never>, Record<never, never>>,
    '/posts/markdown-huanhangyuf': RouteRecordInfo<'/posts/markdown-huanhangyuf', '/posts/markdown-huanhangyuf', Record<never, never>, Record<never, never>>,
    '/posts/markdown-qiangdiaoyufa': RouteRecordInfo<'/posts/markdown-qiangdiaoyufa', '/posts/markdown-qiangdiaoyufa', Record<never, never>, Record<never, never>>,
    '/posts/markdown-sulanbiao': RouteRecordInfo<'/posts/markdown-sulanbiao', '/posts/markdown-sulanbiao', Record<never, never>, Record<never, never>>,
    '/posts/telegram-music': RouteRecordInfo<'/posts/telegram-music', '/posts/telegram-music', Record<never, never>, Record<never, never>>,
    '/posts/tgtalk-deploy': RouteRecordInfo<'/posts/tgtalk-deploy', '/posts/tgtalk-deploy', Record<never, never>, Record<never, never>>,
    '/posts/umami-deploy': RouteRecordInfo<'/posts/umami-deploy', '/posts/umami-deploy', Record<never, never>, Record<never, never>>,
    '/posts/waline-deploy': RouteRecordInfo<'/posts/waline-deploy', '/posts/waline-deploy', Record<never, never>, Record<never, never>>,
    '/posts/zyfx-drop': RouteRecordInfo<'/posts/zyfx-drop', '/posts/zyfx-drop', Record<never, never>, Record<never, never>>,
    '/posts/zyfx-toolooz': RouteRecordInfo<'/posts/zyfx-toolooz', '/posts/zyfx-toolooz', Record<never, never>, Record<never, never>>,
    '/search/': RouteRecordInfo<'/search/', '/search', Record<never, never>, Record<never, never>>,
    '/tags/': RouteRecordInfo<'/tags/', '/tags', Record<never, never>, Record<never, never>>,
    '/talk/': RouteRecordInfo<'/talk/', '/talk', Record<never, never>, Record<never, never>>,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the volar plugin to automatically type useRoute()
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'valaxy-theme-custom/pages/index.vue': {
      routes: '/'
      views: never
    }
    'node_modules/.pnpm/valaxy@0.26.6_@babel+parser_2c27a91d13cce138c2eb328491f950f5/node_modules/valaxy/client/pages/[...path].vue': {
      routes: '/[...path]'
      views: never
    }
    'pages/404.md': {
      routes: '/404'
      views: never
    }
    'pages/about/index.md': {
      routes: '/about/'
      views: never
    }
    'pages/albums/index.md': {
      routes: '/albums/'
      views: never
    }
    'pages/albums/minecraft.md': {
      routes: '/albums/minecraft'
      views: never
    }
    'pages/albums/omori.md': {
      routes: '/albums/omori'
      views: never
    }
    'pages/archives/index.md': {
      routes: '/archives/'
      views: never
    }
    'pages/bangumi/index.md': {
      routes: '/bangumi/'
      views: never
    }
    'pages/categories/index.md': {
      routes: '/categories/'
      views: never
    }
    'pages/fc/index.md': {
      routes: '/fc/'
      views: never
    }
    'pages/links/index.md': {
      routes: '/links/'
      views: never
    }
    'pages/moment/index.md': {
      routes: '/moment/'
      views: never
    }
    'valaxy-theme-custom/pages/page/[page].vue': {
      routes: '/page/[page]'
      views: never
    }
    'pages/policies/privacy.md': {
      routes: '/policies/privacy'
      views: never
    }
    'pages/posts/git-tongbu.md': {
      routes: '/posts/git-tongbu'
      views: never
    }
    'pages/posts/hexo-beiwang.md': {
      routes: '/posts/hexo-beiwang'
      views: never
    }
    'pages/posts/markdown-biaotiyufa.md': {
      routes: '/posts/markdown-biaotiyufa'
      views: never
    }
    'pages/posts/markdown-duanluoyufa.md': {
      routes: '/posts/markdown-duanluoyufa'
      views: never
    }
    'pages/posts/markdown-dulanbiao.md': {
      routes: '/posts/markdown-dulanbiao'
      views: never
    }
    'pages/posts/markdown-huanhangyuf.md': {
      routes: '/posts/markdown-huanhangyuf'
      views: never
    }
    'pages/posts/markdown-qiangdiaoyufa.md': {
      routes: '/posts/markdown-qiangdiaoyufa'
      views: never
    }
    'pages/posts/markdown-sulanbiao.md': {
      routes: '/posts/markdown-sulanbiao'
      views: never
    }
    'pages/posts/telegram-music.md': {
      routes: '/posts/telegram-music'
      views: never
    }
    'pages/posts/tgtalk-deploy.md': {
      routes: '/posts/tgtalk-deploy'
      views: never
    }
    'pages/posts/umami-deploy.md': {
      routes: '/posts/umami-deploy'
      views: never
    }
    'pages/posts/waline-deploy.md': {
      routes: '/posts/waline-deploy'
      views: never
    }
    'pages/posts/zyfx-drop.md': {
      routes: '/posts/zyfx-drop'
      views: never
    }
    'pages/posts/zyfx-toolooz.md': {
      routes: '/posts/zyfx-toolooz'
      views: never
    }
    'pages/search/index.md': {
      routes: '/search/'
      views: never
    }
    'pages/tags/index.md': {
      routes: '/tags/'
      views: never
    }
    'pages/talk/index.md': {
      routes: '/talk/'
      views: never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the volar plugin to automatically type useRoute()
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
